version: '3.2'
services:
  frontend:
    build: .
    image: react-wiseekr
    ports:
      - "8080:80"
    restart: always
  api:
    build: ../wiseekr-api
    image: wiseekr-api
    volumes:
      - type: volume
        source: data
        target: /data
    env_file: .env.api
    environment:
      DATABASE_URL: mysql+pymysql://wiseekr:wiseekr654#@db/wiseekr
    restart: always
  db:
    image: mariadb:10
    healthcheck:
      test:
        - "CMD"
        - "mysqladmin"
        - "ping"
        - "-h"
        - "localhost"
        - "-uroot"
        - "-pamboss"
      interval: 30s
      timeout: 30s
      retries: 5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: amboss
      MARIADB_DATABASE: wiseekr
      MARIADB_USER: wiseekr
      MARIADB_PASSWORD: wiseekr654#
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
volumes:
  data:
  db_data: